name: Test
on: [push, pull_request]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Neovim
        uses: rhysd/action-setup-vim@v1
        with:
          version: stable
        run: |
          apt-get install neovim
      - name: Install plenary
        run: |
          git clone https://github.com/nvim-lua/plenary.nvim ~/.local/share/nvim/plugged/plenary.nvim
      - name: Run tests
        run: |
          nvim --headless -c "PlenaryBustedDirectory tests/plenary { minimal_init = 'tests/minimal_init.lua' }" -c "qa"
